name: Build

on: [push]

jobs:
  build:
    env:
      SEC_IP: ${{ secrets.IP }}
      SEC_KEY: ${{ secrets.KEY }}
      SEC_USERNAME: ${{ secrets.USERNAME }}
      SEC_PASSWORD: ${{ secrets.PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configuration environment
        run: |
          mkdir -p ~/.ssh/
          echo "$SEC_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t ed25519 -p 56789 $SEC_IP >> ~/.ssh/known_hosts
      - name: Docker login
        run: |
          docker login -u $SEC_USERNAME -p $SEC_PASSWORD
      - name: Docker build
        run: |
          docker build -t ryuuinc/generar .
      - name: Docker publish
        run: |
          docker push ryuuinc/generar
      - name: SSH stuff
        run: |
          ssh root@$SEC_IP -p 56789 "docker pull ryuuinc/generar"
